
# ft sensor initialize

sampling_time : 2.0
control_time : 0.002 #2ms, 500Hz

#low pass filter
lpf_force_cutoff_frequency  : 0
lpf_torque_cutoff_frequency : 0

#high pass filter
hpf_force_cutoff_frequency  : 0
hpf_torque_cutoff_frequency : 0


#ft sensor kalman filter modeling 

gain_Q : 0 
gain_R : 500


#ft collision detection parameter
# force  
fx_k : 1
fx_high_limit : 12
fx_low_limit : -22

fy_k : 0
fy_high_limit : 0
fy_low_limit :  0

fz_k : 0
fz_high_limit : 0
fz_low_limit :  0

## torque 
tx_k : 0
tx_high_limit : 0
tx_low_limit :  0

ty_k : 0
ty_high_limit : 0
ty_low_limit :  0

tz_k : 0
tz_high_limit : 0
tz_low_limit : 0




