#seconds
motion_start_time: 
  0: [10]
  1: [7]
  2: [10]


#TCP frame [M] / degree ZYX angle 
motion_task: 
#  0: [-0.155, 0, 0, 0, 0, 0]
#  1: [0, 0, 0.038, 0, 0, 0]
#  2: [0, 0, 0, 0, 30, 0]

  0: [0, 0, 0, 0, -20, 0]
  1: [0, 0, 0, 0, -20, 0]
  2: [0, 0, 0, 0, -20, 0]



 
#TCP frame [N]
desired_force:
  0: [0,0,0,0,0,0]
  1: [0,0,0,0,0,0]
  2: [0,0,0,0,0,0]






