#seconds
motion_start_time: 
  0: [7]
  1: [7]
  2: [2]
  3: [7]

#TCP frame [mm]
motion_task: 
  0: [0, 0, 0, 0, 0, 0]
  1: [0, 0.1, 0, 0, 0, 0]
  2: [0, 0, 0, 0, 0, 0]
  3: [0, 0, 0.1, 0, 0, 0]

#TCP frame [N]
desired_force:
  0: [0,0,0]
  1: [0,0,0]
  2: [5,0,0]
  3: [0,0,0]


