#seconds
motion_start_time: 
  0: [7]
  1: [7]
  2: [7]

#TCP frame [M] / degree ZYX angle 
motion_task: 
  0: [0.05, 0, 0, 0, 0, 0]
  1: [0.05, 0.05, 0, 0, 0, 0]
  2: [0.05, 0.05, 0.05, 0, 10, 0]

 
#TCP frame [N]
desired_force:
  0: [0,0,0,0,0,0]
  1: [0,0,0,0,0,0]
  2: [0,0,0,0,0,0]




