#seconds
motion_start_time: 
  0: [7]
  1: [7]
  2: [7]
  3: [7]
  4: [7]

#TCP frame [M] / degree XYZ angle 
motion_task: 
  0: [-0.17, 0, 0, 0, 0, 0]
  1: [0, 0, 0.05, 0, 0, 0]
  2: [0, 0, 0, 0, 0, 10]
  3: [0, 0, 0, 0, 45, 0]
  4: [0, 0, 0, 50, 0, 0]


 
#TCP frame [N]
desired_force:
  0: [0,0,0,0,0,0]
  1: [0,0,0,0,0,0]
  2: [0,0,0,0,0,0]
  3: [0,0,0,0,0,0]
  4: [0,0,0,0,0,0]





